# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Kyle Stratis
tagline:             'Software Developer in Tallahassee, FL'
description:         'On an eternal quest to build and learn'
url:                 http://kylestratis.com
giturl:				       http://kylestratis.github.io
baseurl:             /
paginate:            5
rss:                 atom.xml

# About/contact
author:
  name:             Kyle Stratis
  github:           kylestratis
  email:            kylestratis@gmail.com
  linkedin:         kylestratis
  goodreads:        kylestratis
  google_scholar:   http://scholar.google.com/citations?hl=en&user=-WO2ezMAAAAJ
  gravatar_md5:     89b28e44e0840bc12ece69b274c29606

# Custom vars
version:             1.0.1

github:
  repo:           https://github.com/kylestratis/kylestratis.github.io